name: flutter_notes_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Hive for local storage (NoSQL database)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Intl for date formatting
  intl: ^0.18.1
  # Path provider to find where to store data
  path_provider: ^2.1.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Code generators for Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
